package in.deepstudio.expensemanager.domain;

// Generated Apr 26, 2015 4:50:10 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

/**
 * ExpenseBillBook generated by hbm2java
 */
@Entity
@Table(name = "expense_bill_book",schema="public")
public class ExpenseBillBook implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long expenseBillBookId;
	private ExpenseType expenseType;
	private Date expenseDate;
	private String expenseAmt;
	private Date createdDate;
	private Date updatedDate;
	private String ipAddress;
	private String expenseDesc;

	public ExpenseBillBook() {
	}

	public ExpenseBillBook(Long expenseBillBookId, ExpenseType expenseType,
			Date expenseDate, String expenseAmt, Date createdDate,
			Date updatedDate, String ipAddress, String expenseDesc) {
		this.expenseBillBookId = expenseBillBookId;
		this.expenseType = expenseType;
		this.expenseDate = expenseDate;
		this.expenseAmt = expenseAmt;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.ipAddress = ipAddress;
		this.expenseDesc = expenseDesc;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "expense_bill_book_id", unique = true, nullable = false)
	public Long getExpenseBillBookId() {
		return this.expenseBillBookId;
	}

	public void setExpenseBillBookId(Long expenseBillBookId) {
		this.expenseBillBookId = expenseBillBookId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "expense_type_id", nullable = false)
	public ExpenseType getExpenseType() {
		return this.expenseType;
	}

	public void setExpenseType(ExpenseType expenseType) {
		this.expenseType = expenseType;
	}

	@DateTimeFormat(iso=ISO.DATE,pattern="dd/MM/yyyy")
	@Column(name = "expense_date", nullable = false, length = 19)
	public Date getExpenseDate() {
		return this.expenseDate;
	}

	public void setExpenseDate(Date expenseDate) {
		this.expenseDate = expenseDate;
	}

	@Column(name = "expense_amt", nullable = false, length = 10)
	public String getExpenseAmt() {
		return this.expenseAmt;
	}

	public void setExpenseAmt(String expenseAmt) {
		this.expenseAmt = expenseAmt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "ip_address", nullable = false, length = 25)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@Column(name = "expense_desc", nullable = false, length = 250)
	public String getExpenseDesc() {
		return this.expenseDesc;
	}

	public void setExpenseDesc(String expenseDesc) {
		this.expenseDesc = expenseDesc;
	}

}
