package in.deepstudio.expensemanager.domain;

// Generated Apr 26, 2015 4:50:10 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ExpenseType generated by hbm2java
 */
@Entity
@Table(name = "expense_type",schema="public")
public class ExpenseType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long expenseTypeId;
	private String expenseTypeName;
	private String expenseTypeDesc;
	private Date createdDate;
	private Date updatedDate;
	private String ipAddress;
	private Set<ExpenseBillBook> expenseBillBooks = new HashSet<ExpenseBillBook>(0);

	public ExpenseType() {
	}

	public ExpenseType(Long expenseTypeId, String expenseTypeName,
			Date createdDate, Date updatedDate, String ipAddress) {
		this.expenseTypeId = expenseTypeId;
		this.expenseTypeName = expenseTypeName;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.ipAddress = ipAddress;
	}

	public ExpenseType(Long expenseTypeId, String expenseTypeName,
			String expenseTypeDesc, Date createdDate, Date updatedDate,
			String ipAddress, Set<ExpenseBillBook> expenseBillBooks) {
		this.expenseTypeId = expenseTypeId;
		this.expenseTypeName = expenseTypeName;
		this.expenseTypeDesc = expenseTypeDesc;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.ipAddress = ipAddress;
		this.expenseBillBooks = expenseBillBooks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "expense_type_id", unique = true, nullable = false)
	public Long getExpenseTypeId() {
		return this.expenseTypeId;
	}

	public void setExpenseTypeId(Long expenseTypeId) {
		this.expenseTypeId = expenseTypeId;
	}

	@Column(name = "expense_type_name", nullable = false, length = 45)
	public String getExpenseTypeName() {
		return this.expenseTypeName;
	}

	public void setExpenseTypeName(String expenseTypeName) {
		this.expenseTypeName = expenseTypeName;
	}

	@Column(name = "expense_type_desc", length = 200)
	public String getExpenseTypeDesc() {
		return this.expenseTypeDesc;
	}

	public void setExpenseTypeDesc(String expenseTypeDesc) {
		this.expenseTypeDesc = expenseTypeDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "ip_address", nullable = false, length = 25)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "expenseType")
	public Set<ExpenseBillBook> getExpenseBillBooks() {
		return this.expenseBillBooks;
	}

	public void setExpenseBillBooks(Set<ExpenseBillBook> expenseBillBooks) {
		this.expenseBillBooks = expenseBillBooks;
	}

}
