INSERT INTO frame_info (created_date, frame_desc, frame_type, frame_type_photo, ip_address, updated_date) VALUES (CURDATE(),'','Single Mount Framing','','',CURDATE());
INSERT INTO frame_info (created_date, frame_desc, frame_type, frame_type_photo, ip_address, updated_date) VALUES (CURDATE(),'','Double Mounted Or Sandwich Framing','','',CURDATE());
INSERT INTO frame_info (created_date, frame_desc, frame_type, frame_type_photo, ip_address, updated_date) VALUES (CURDATE(),'','Framing On Lamination/lamination Framing','','',CURDATE());
INSERT INTO frame_info (created_date, frame_desc, frame_type, frame_type_photo, ip_address, updated_date) VALUES (CURDATE(),'','Size to Size Framing/Direct Framing','','',CURDATE());
INSERT INTO frame_info (created_date, frame_desc, frame_type, frame_type_photo, ip_address, updated_date) VALUES (CURDATE(),'','Other','','',CURDATE());
INSERT INTO frame_number (created_date, frame_desc, frame_number, frame_number_photos, ip_address, updated_date) VALUES (CURDATE(),'','1','','',CURDATE());
INSERT INTO frame_number (created_date, frame_desc, frame_number, frame_number_photos, ip_address, updated_date) VALUES (CURDATE(),'','Other','','',CURDATE());
INSERT INTO frame_thickness (created_date, frame_desc, frame_measurements_type, frame_thickness_size, ip_address, updated_date) VALUES (CURDATE(),'','inches','0.5','',CURDATE());
INSERT INTO frame_thickness (created_date, frame_desc, frame_measurements_type, frame_thickness_size, ip_address, updated_date) VALUES (CURDATE(),'','inches','0.75','',CURDATE());
INSERT INTO frame_thickness (created_date, frame_desc, frame_measurements_type, frame_thickness_size, ip_address, updated_date) VALUES (CURDATE(),'','inches','1','',CURDATE());
INSERT INTO frame_thickness (created_date, frame_desc, frame_measurements_type, frame_thickness_size, ip_address, updated_date) VALUES (CURDATE(),'','inches','1.25','',CURDATE());
INSERT INTO frame_thickness (created_date, frame_desc, frame_measurements_type, frame_thickness_size, ip_address, updated_date) VALUES (CURDATE(),'','inches','1.50','',CURDATE());
INSERT INTO frame_thickness (created_date, frame_desc, frame_measurements_type, frame_thickness_size, ip_address, updated_date) VALUES (CURDATE(),'','inches','1.75','',CURDATE());
INSERT INTO frame_thickness (created_date, frame_desc, frame_measurements_type, frame_thickness_size, ip_address, updated_date) VALUES (CURDATE(),'','inches','2.50','',CURDATE());
INSERT INTO frame_thickness (created_date, frame_desc, frame_measurements_type, frame_thickness_size, ip_address, updated_date) VALUES (CURDATE(),'','inches','Other','',CURDATE());
INSERT INTO frame_size (created_date, frame_desc, frame_measurements_type, frame_size_chart, frame_size_height, frame_size_width, ip_address, updated_date) VALUES (CURDATE(),'','inches','','8','6','',CURDATE());
INSERT INTO frame_size (created_date, frame_desc, frame_measurements_type, frame_size_chart, frame_size_height, frame_size_width, ip_address, updated_date) VALUES (CURDATE(),'','inches','','10','8','',CURDATE());
INSERT INTO frame_size (created_date, frame_desc, frame_measurements_type, frame_size_chart, frame_size_height, frame_size_width, ip_address, updated_date) VALUES (CURDATE(),'','inches','','12','8','',CURDATE());
INSERT INTO frame_size (created_date, frame_desc, frame_measurements_type, frame_size_chart, frame_size_height, frame_size_width, ip_address, updated_date) VALUES (CURDATE(),'','inches','','12','10','',CURDATE());
INSERT INTO frame_size (created_date, frame_desc, frame_measurements_type, frame_size_chart, frame_size_height, frame_size_width, ip_address, updated_date) VALUES (CURDATE(),'','inches','','15','10','',CURDATE());
INSERT INTO frame_size (created_date, frame_desc, frame_measurements_type, frame_size_chart, frame_size_height, frame_size_width, ip_address, updated_date) VALUES (CURDATE(),'','inches','','15','12','',CURDATE());
INSERT INTO frame_size (created_date, frame_desc, frame_measurements_type, frame_size_chart, frame_size_height, frame_size_width, ip_address, updated_date) VALUES (CURDATE(),'','inches','','18','12','',CURDATE());
INSERT INTO frame_size (created_date, frame_desc, frame_measurements_type, frame_size_chart, frame_size_height, frame_size_width, ip_address, updated_date) VALUES (CURDATE(),'','inches','','20','16','',CURDATE());
INSERT INTO frame_size (created_date, frame_desc, frame_measurements_type, frame_size_chart, frame_size_height, frame_size_width, ip_address, updated_date) VALUES (CURDATE(),'','inches','','24','12','',CURDATE());
INSERT INTO frame_size (created_date, frame_desc, frame_measurements_type, frame_size_chart, frame_size_height, frame_size_width, ip_address, updated_date) VALUES (CURDATE(),'','inches','','24','16','',CURDATE());
INSERT INTO frame_size (created_date, frame_desc, frame_measurements_type, frame_size_chart, frame_size_height, frame_size_width, ip_address, updated_date) VALUES (CURDATE(),'','inches','','30','12','',CURDATE());
INSERT INTO frame_size (created_date, frame_desc, frame_measurements_type, frame_size_chart, frame_size_height, frame_size_width, ip_address, updated_date) VALUES (CURDATE(),'','inches','','36','12','',CURDATE());
INSERT INTO frame_size (created_date, frame_desc, frame_measurements_type, frame_size_chart, frame_size_height, frame_size_width, ip_address, updated_date) VALUES (CURDATE(),'','inches','','24','20','',CURDATE());
INSERT INTO frame_size (created_date, frame_desc, frame_measurements_type, frame_size_chart, frame_size_height, frame_size_width, ip_address, updated_date) VALUES (CURDATE(),'','inches','','30','20','',CURDATE());
INSERT INTO frame_size (created_date, frame_desc, frame_measurements_type, frame_size_chart, frame_size_height, frame_size_width, ip_address, updated_date) VALUES (CURDATE(),'','inches','','36','24','',CURDATE());
INSERT INTO frame_size (created_date, frame_desc, frame_measurements_type, frame_size_chart, frame_size_height, frame_size_width, ip_address, updated_date) VALUES (CURDATE(),'','inches','','0','0','',CURDATE());
INSERT INTO frame_client_type (client_desc, client_type_name, created_date, ip_address, updated_date) VALUES ('','Photographer',CURDATE(),'',CURDATE());
INSERT INTO frame_client_type (client_desc, client_type_name, created_date, ip_address, updated_date) VALUES ('','Regular Customer',CURDATE(),'',CURDATE());
INSERT INTO frame_client_type (client_desc, client_type_name, created_date, ip_address, updated_date) VALUES ('','Other',CURDATE(),'',CURDATE());
