package in.deepstudio.pvq.domain;

// Generated Apr 22, 2015 12:55:13 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PvqBillConcernDetail generated by hbm2java
 */
@Entity
@Table(name = "pvq_bill_concern_detail")
public class PvqBillConcernDetail implements java.io.Serializable {	

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long pvqBillConcernDetailId;
	private PvqBillInfo pvqBillInfo;
	private PvqConcernType pvqConcernType;
	private PvqConcernRate pvqConcernRate;
	private String pvqBillConcernDetailDesc;
	private Integer quantity;
	private Integer actualRate;
	private Integer sellingRate;

	public PvqBillConcernDetail() {
	}

	public PvqBillConcernDetail(Long pvqBillConcernDetailId,
			PvqBillInfo pvqBillInfo, PvqConcernType pvqConcernType,PvqConcernRate pvqConcernRate,
			Integer quantity, Integer actualRate, Integer sellingRate) {
		super();
		this.pvqBillConcernDetailId = pvqBillConcernDetailId;
		this.pvqBillInfo = pvqBillInfo;
		this.pvqConcernType = pvqConcernType;
		this.pvqConcernRate = pvqConcernRate;
		this.quantity = quantity;
		this.actualRate = actualRate;
		this.sellingRate = sellingRate;
	}

	public PvqBillConcernDetail(Long pvqBillConcernDetailId,
			PvqBillInfo pvqBillInfo, PvqConcernType pvqConcernType,PvqConcernRate pvqConcernRate,
			String pvqBillConcernDetailDesc, Integer quantity,
			Integer actualRate, Integer sellingRate) {
		super();
		this.pvqBillConcernDetailId = pvqBillConcernDetailId;
		this.pvqBillInfo = pvqBillInfo;
		this.pvqConcernType = pvqConcernType;
		this.pvqConcernRate = pvqConcernRate;
		this.pvqBillConcernDetailDesc = pvqBillConcernDetailDesc;
		this.quantity = quantity;
		this.actualRate = actualRate;
		this.sellingRate = sellingRate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "pvq_bill_concern_detail_id", unique = true, nullable = false)
	public Long getPvqBillConcernDetailId() {
		return this.pvqBillConcernDetailId;
	}

	public void setPvqBillConcernDetailId(Long pvqBillConcernDetailId) {
		this.pvqBillConcernDetailId = pvqBillConcernDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pvq_bill_detail_id", nullable = false)
	public PvqBillInfo getPvqBillInfo() {
		return this.pvqBillInfo;
	}

	public void setPvqBillInfo(PvqBillInfo pvqBillInfo) {
		this.pvqBillInfo = pvqBillInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pvq_concern_type_id", nullable = false)
	public PvqConcernType getPvqConcernType() {
		return this.pvqConcernType;
	}
	
	public void setPvqConcernType(PvqConcernType pvqConcernType) {
		this.pvqConcernType = pvqConcernType;
	}
	
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pvq_concern_rate_id", nullable = false)
	public PvqConcernRate getPvqConcernRate() {
		return this.pvqConcernRate;
	}
	
	public void setPvqConcernRate(PvqConcernRate pvqConcernRate) {
		this.pvqConcernRate = pvqConcernRate;
	}

	@Column(name = "pvq_bill_concern_detail_desc", length = 200)
	public String getPvqBillConcernDetailDesc() {
		return this.pvqBillConcernDetailDesc;
	}

	public void setPvqBillConcernDetailDesc(String pvqBillConcernDetailDesc) {
		this.pvqBillConcernDetailDesc = pvqBillConcernDetailDesc;
	}

	@Column(name = "quantity", nullable = false, length = 10)
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	@Column(name = "actual_rate", nullable = false, length = 10)
	public Integer getActualRate() {
		return this.actualRate;
	}

	public void setActualRate(Integer actualRate) {
		this.actualRate = actualRate;
	}

	@Column(name = "selling_rate", nullable = false, length = 10)
	public Integer getSellingRate() {
		return this.sellingRate;
	}

	public void setSellingRate(Integer sellingRate) {
		this.sellingRate = sellingRate;
	}

}
