package in.deepstudio.pvq.domain;

// Generated Apr 28, 2015 5:12:30 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

/**
 * PvqBillOrderSummary generated by hbm2java
 */
@Entity
@Table(name = "pvq_bill_order_summary")
public class PvqBillOrderSummary implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long pvqBillOrderSummaryId;
	private PvqBillInfo pvqBillInfo;
	private Date pvqBillOrderSummaryDate;
	private String pvqBillOrderSummaryPhotographersQt;
	private String pvqBillOrderSummaryVideographersQt;
	private String pvqBillOrderSummaryCrainQt;
	private String pvqBillOrderSummaryLedQt;
	private String pvqBillOrderSummaryEventType;
	private String pvqBillOrderSummaryTime;
	
	public PvqBillOrderSummary() {
	}

	public PvqBillOrderSummary(Long pvqBillOrderSummaryId,
			PvqConcernType pvqConcernType, Date pvqBillOrderSummaryDate,
			String pvqBillOrderSummaryEventType,
			String pvqBillOrderSummaryTime,String pvqBillOrderSummaryPhotographersQt,String pvqBillOrderSummaryVideographersQt,
			String pvqBillOrderSummaryCrainQt,String pvqBillOrderSummaryLedQt,
			String pvqConcernTypeDesc) {
		this.pvqBillOrderSummaryId = pvqBillOrderSummaryId;
		this.pvqBillOrderSummaryDate = pvqBillOrderSummaryDate;
		this.pvqBillOrderSummaryEventType = pvqBillOrderSummaryEventType;
		this.pvqBillOrderSummaryTime = pvqBillOrderSummaryTime;
		this.pvqBillOrderSummaryPhotographersQt = pvqBillOrderSummaryPhotographersQt;
		this.pvqBillOrderSummaryVideographersQt = pvqBillOrderSummaryVideographersQt;
		this.pvqBillOrderSummaryCrainQt = pvqBillOrderSummaryCrainQt;
		this.pvqBillOrderSummaryLedQt = pvqBillOrderSummaryLedQt;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "pvq_bill_order_summary_id", unique = true, nullable = false)
	public Long getPvqBillOrderSummaryId() {
		return this.pvqBillOrderSummaryId;
	}

	public void setPvqBillOrderSummaryId(Long pvqBillOrderSummaryId) {
		this.pvqBillOrderSummaryId = pvqBillOrderSummaryId;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pvq_bill_detail_id", nullable = false)
	public PvqBillInfo getPvqBillInfo() {
		return this.pvqBillInfo;
	}

	public void setPvqBillInfo(PvqBillInfo pvqBillInfo) {
		this.pvqBillInfo = pvqBillInfo;
	}
	
	@DateTimeFormat(iso=ISO.DATE,pattern="dd/MM/yyyy")
	@Column(name = "pvq_bill_order_summary_date", nullable = false, length = 10)
	public Date getPvqBillOrderSummaryDate() {
		return this.pvqBillOrderSummaryDate;
	}

	public void setPvqBillOrderSummaryDate(Date pvqBillOrderSummaryDate) {
		this.pvqBillOrderSummaryDate = pvqBillOrderSummaryDate;
	}

	@Column(name = "pvq_bill_order_summary_event_type", nullable = false, length = 45)
	public String getPvqBillOrderSummaryEventType() {
		return this.pvqBillOrderSummaryEventType;
	}

	public void setPvqBillOrderSummaryEventType(
			String pvqBillOrderSummaryEventType) {
		this.pvqBillOrderSummaryEventType = pvqBillOrderSummaryEventType;
	}

	@Column(name = "pvq_bill_order_summary_time", nullable = false, length = 45)
	public String getPvqBillOrderSummaryTime() {
		return this.pvqBillOrderSummaryTime;
	}

	public void setPvqBillOrderSummaryTime(String pvqBillOrderSummaryTime) {
		this.pvqBillOrderSummaryTime = pvqBillOrderSummaryTime;
	}

	@Column(name = "pvq_bill_order_summary_photographers_qt", nullable = true, length = 45)
	public String getPvqBillOrderSummaryPhotographersQt() {
		return pvqBillOrderSummaryPhotographersQt;
	}

	public void setPvqBillOrderSummaryPhotographersQt(
			String pvqBillOrderSummaryPhotographersQt) {
		this.pvqBillOrderSummaryPhotographersQt = pvqBillOrderSummaryPhotographersQt;
	}

	@Column(name = "pvq_bill_order_summary_videographers_qt", nullable = true, length = 45)
	public String getPvqBillOrderSummaryVideographersQt() {
		return pvqBillOrderSummaryVideographersQt;
	}

	public void setPvqBillOrderSummaryVideographersQt(
			String pvqBillOrderSummaryVideographersQt) {
		this.pvqBillOrderSummaryVideographersQt = pvqBillOrderSummaryVideographersQt;
	}

	@Column(name = "pvq_bill_order_summary_crain_qt", nullable = true, length = 45)
	public String getPvqBillOrderSummaryCrainQt() {
		return pvqBillOrderSummaryCrainQt;
	}

	public void setPvqBillOrderSummaryCrainQt(String pvqBillOrderSummaryCrainQt) {
		this.pvqBillOrderSummaryCrainQt = pvqBillOrderSummaryCrainQt;
	}

	@Column(name = "pvq_bill_order_summary_led_qt", nullable = true, length = 45)
	public String getPvqBillOrderSummaryLedQt() {
		return pvqBillOrderSummaryLedQt;
	}

	public void setPvqBillOrderSummaryLedQt(String pvqBillOrderSummaryLedQt) {
		this.pvqBillOrderSummaryLedQt = pvqBillOrderSummaryLedQt;
	}
	
	

}
