package in.deepstudio.pvq.domain;

// Generated Apr 22, 2015 12:55:13 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PvqBillPaymentHistory generated by hbm2java
 */
@Entity
@Table(name = "pvq_bill_payment_history",schema="public")
public class PvqBillPaymentHistory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long pvqBillPaymentHistoryId;
	private PvqBillInfo pvqBillInfo;
	private int pvqBillPaymentVersion;
	private String depositeAmount;
	

	public PvqBillPaymentHistory() {
	}

	public PvqBillPaymentHistory(Long pvqBillPaymentHistoryId,
			PvqBillInfo pvqBillInfo, int pvqBillPaymentVersion,
			String depositeAmount) {
		super();
		this.pvqBillPaymentHistoryId = pvqBillPaymentHistoryId;
		this.pvqBillInfo = pvqBillInfo;
		this.pvqBillPaymentVersion = pvqBillPaymentVersion;
		this.depositeAmount = depositeAmount;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "pvq_bill_payment_history_id", unique = true, nullable = false)
	public Long getPvqBillPaymentHistoryId() {
		return this.pvqBillPaymentHistoryId;
	}

	public void setPvqBillPaymentHistoryId(Long pvqBillPaymentHistoryId) {
		this.pvqBillPaymentHistoryId = pvqBillPaymentHistoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pvq_bill_detail_id", nullable = false)
	public PvqBillInfo getPvqBillInfo() {
		return this.pvqBillInfo;
	}

	public void setPvqBillInfo(PvqBillInfo pvqBillInfo) {
		this.pvqBillInfo = pvqBillInfo;
	}

	@Column(name = "pvq_bill_payment_version", nullable = false)
	public int getPvqBillPaymentVersion() {
		return this.pvqBillPaymentVersion;
	}

	public void setPvqBillPaymentVersion(int pvqBillPaymentVersion) {
		this.pvqBillPaymentVersion = pvqBillPaymentVersion;
	}

	@Column(name = "deposite_amount", nullable = false, length = 10)
	public String getDepositeAmount() {
		return this.depositeAmount;
	}

	public void setDepositeAmount(String depositeAmount) {
		this.depositeAmount = depositeAmount;
	}
}
