package in.deepstudio.pvq.domain;

// Generated Apr 22, 2015 12:55:13 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

/**
 * PvqBillInfo generated by hbm2java
 */
@Entity
@Table(name = "pvq_bill_info",schema="public")
public class PvqBillInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long pvqBillDetailId;
	private String billNumber;
	private String custName;
	private String custMobno;
	private String custAddress;
	private Date billDate;
	private String depositeAmount="0";
	private String quatationBillAmount="0";
	private String totalPaidAmount="0";
	private String dueAmount="0";
	private String orderStatus;
	private String billStatus;
	private Date createdDate;
	private Date updatedDate;
	private String ipAddress;
	private List<PvqBillPaymentHistory> pvqBillPaymentHistories = new ArrayList<PvqBillPaymentHistory>(0);
	private List<PvqBillOrderSummary> pvqBillOrderSummary = new ArrayList<PvqBillOrderSummary>(0);
	private List<PvqBillConcernDetail> pvqBillConcernDetails = new ArrayList<PvqBillConcernDetail>(0);

	public PvqBillInfo() {
	}

	public PvqBillInfo(Long pvqBillDetailId, String billNumber, String custName,
			Date billDate, String quatationBillAmount, String totalPaidAmount,String dueAmount,
			String orderStatus ,String billStatus,
			Date createdDate, Date updatedDate, String ipAddress) {
		super();
		this.pvqBillDetailId = pvqBillDetailId;
		this.billNumber = billNumber;
		this.custName = custName;
		this.billDate = billDate;
		this.quatationBillAmount = quatationBillAmount;
		this.totalPaidAmount = totalPaidAmount;
		this.dueAmount = dueAmount;
		this.orderStatus = orderStatus;
		this.billStatus = billStatus;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.ipAddress = ipAddress;
	}

	public PvqBillInfo(Long pvqBillDetailId, String billNumber, String custName,
			String custMobno, String custAddress, Date billDate,
			String quatationBillAmount,String totalPaidAmount, String dueAmount,String orderStatus , String billStatus, Date createdDate,
			Date updatedDate, String ipAddress,
			List<PvqBillPaymentHistory> pvqBillPaymentHistories,
			List<PvqBillOrderSummary> pvqBillOrderSummary,
			List<PvqBillConcernDetail> pvqBillConcernDetails) {
		super();
		this.pvqBillDetailId = pvqBillDetailId;
		this.billNumber = billNumber;
		this.custName = custName;
		this.custMobno = custMobno;
		this.custAddress = custAddress;
		this.billDate = billDate;
		this.quatationBillAmount = quatationBillAmount;
		this.totalPaidAmount=totalPaidAmount;
		this.dueAmount = dueAmount;
		this.orderStatus = orderStatus;
		this.billStatus = billStatus;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.ipAddress = ipAddress;
		this.pvqBillPaymentHistories = pvqBillPaymentHistories;
		this.pvqBillConcernDetails = pvqBillConcernDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "pvq_bill_detail_id", unique = true, nullable = false)
	public Long getPvqBillDetailId() {
		return this.pvqBillDetailId;
	}

	public void setPvqBillDetailId(Long pvqBillDetailId) {
		this.pvqBillDetailId = pvqBillDetailId;
	}

	@Column(name = "bill_number", nullable = false, length = 15)
	public String getBillNumber() {
		return this.billNumber;
	}

	public void setBillNumber(String billNumber) {
		this.billNumber = billNumber;
	}

	@Column(name = "cust_name", nullable = false, length = 45)
	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	@Column(name = "cust_mobno", length = 15)
	public String getCustMobno() {
		return this.custMobno;
	}

	public void setCustMobno(String custMobno) {
		this.custMobno = custMobno;
	}

	@Column(name = "cust_address", length = 100)
	public String getCustAddress() {
		return this.custAddress;
	}

	public void setCustAddress(String custAddress) {
		this.custAddress = custAddress;
	}

	@DateTimeFormat(iso=ISO.DATE,pattern="dd/MM/yyyy")
	@Column(name = "bill_date", nullable = false, length = 19)
	public Date getBillDate() {
		return this.billDate;
	}

	public void setBillDate(Date billDate) {
		this.billDate = billDate;
	}

	@Column(name = "quatation_bill_amount", nullable = false, length = 10)
	public String getQuatationBillAmount() {
		return this.quatationBillAmount;
	}

	public void setQuatationBillAmount(String quatationBillAmount) {
		this.quatationBillAmount = quatationBillAmount;
	}
	
	@Column(name = "total_paid_amount", nullable = false, length = 10)
	public String getTotalPaidAmount() {
		return this.totalPaidAmount;
	}

	public void setTotalPaidAmount(String totalPaidAmount) {
		this.totalPaidAmount = totalPaidAmount;
	}
	
	@Column(name = "due_amount", nullable = false, length = 10)
	public String getDueAmount() {
		return this.dueAmount;
	}

	public void setDueAmount(String dueAmount) {
		this.dueAmount = dueAmount;
	}
	
	@Column(name = "bill_status", nullable = false, length = 15)
	public String getBillStatus() {
		return this.billStatus;
	}

	public void setBillStatus(String billStatus) {
		this.billStatus = billStatus;
	}
	
	@Column(name = "order_status", nullable = false, length = 15)
	public String getOrderStatus() {
		return this.orderStatus;
	}

	public void setOrderStatus(String orderStatus) {
		this.orderStatus = orderStatus;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "ip_address", nullable = false, length = 45)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pvqBillInfo",cascade=CascadeType.ALL)
	public List<PvqBillPaymentHistory> getPvqBillPaymentHistories() {
		return this.pvqBillPaymentHistories;
	}

	public void setPvqBillPaymentHistories(
			List<PvqBillPaymentHistory> pvqBillPaymentHistories) {
		this.pvqBillPaymentHistories = pvqBillPaymentHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pvqBillInfo",cascade=CascadeType.ALL)
	public List<PvqBillOrderSummary> getPvqBillOrderSummary() {
		return this.pvqBillOrderSummary;
	}

	public void setPvqBillOrderSummary(
			List<PvqBillOrderSummary> pvqBillOrderSummary) {
		this.pvqBillOrderSummary = pvqBillOrderSummary;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pvqBillInfo",cascade=CascadeType.ALL)
	public List<PvqBillConcernDetail> getPvqBillConcernDetails() {
		return this.pvqBillConcernDetails;
	}

	public void setPvqBillConcernDetails(
			List<PvqBillConcernDetail> pvqBillConcernDetails) {
		this.pvqBillConcernDetails = pvqBillConcernDetails;
	}

	public String getDepositeAmount() {
		return depositeAmount;
	}

	public void setDepositeAmount(String depositeAmount) {
		this.depositeAmount = depositeAmount;
	}

}
