package in.deepstudio.pvq.domain;

// Generated Apr 22, 2015 12:55:13 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PvqConcernType generated by hbm2java
 */
@Entity
@Table(name = "pvq_concern_type", uniqueConstraints = @UniqueConstraint(columnNames = "pvq_concern_type_name"),schema="public")
public class PvqConcernType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long pvqConcernTypeId;
	private String pvqConcernTypeName;
	private String pvqConcernTypeDesc;
	private Date createdDate;
	private Date updatedDate;
	private String ipAddress;
	private Set<PvqBillConcernDetail> pvqBillConcernDetails = new HashSet<PvqBillConcernDetail>(0);
	private Set<PvqConcernRate> pvqConcernRates = new HashSet<PvqConcernRate>(0);

	public PvqConcernType() {
	}

	public PvqConcernType(Long pvqConcernTypeId, String pvqConcernTypeName,
			Date createdDate, Date updatedDate, String ipAddress) {
		this.pvqConcernTypeId = pvqConcernTypeId;
		this.pvqConcernTypeName = pvqConcernTypeName;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.ipAddress = ipAddress;
	}

	public PvqConcernType(Long pvqConcernTypeId, String pvqConcernTypeName,
			String pvqConcernTypeDesc, Date createdDate, Date updatedDate,
			String ipAddress, Set<PvqBillConcernDetail> pvqBillConcernDetails,
			Set<PvqBillOrderSummary> pvqBillOrderSummaries,
			Set<PvqConcernRate> pvqConcernRates) {
		this.pvqConcernTypeId = pvqConcernTypeId;
		this.pvqConcernTypeName = pvqConcernTypeName;
		this.pvqConcernTypeDesc = pvqConcernTypeDesc;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.ipAddress = ipAddress;
		this.pvqBillConcernDetails = pvqBillConcernDetails;
		this.pvqConcernRates = pvqConcernRates;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "pvq_concern_type_id", unique = true, nullable = false)
	public Long getPvqConcernTypeId() {
		return this.pvqConcernTypeId;
	}

	public void setPvqConcernTypeId(Long pvqConcernTypeId) {
		this.pvqConcernTypeId = pvqConcernTypeId;
	}

	@Column(name = "pvq_concern_type_name", nullable = false, length = 45)
	public String getPvqConcernTypeName() {
		return this.pvqConcernTypeName;
	}

	public void setPvqConcernTypeName(String pvqConcernTypeName) {
		this.pvqConcernTypeName = pvqConcernTypeName;
	}

	@Column(name = "pvq_concern_type_desc", length = 45)
	public String getPvqConcernTypeDesc() {
		return this.pvqConcernTypeDesc;
	}

	public void setPvqConcernTypeDesc(String pvqConcernTypeDesc) {
		this.pvqConcernTypeDesc = pvqConcernTypeDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "ip_address", nullable = false, length = 45)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pvqConcernType")
	public Set<PvqBillConcernDetail> getPvqBillConcernDetails() {
		return this.pvqBillConcernDetails;
	}

	public void setPvqBillConcernDetails(
			Set<PvqBillConcernDetail> pvqBillConcernDetails) {
		this.pvqBillConcernDetails = pvqBillConcernDetails;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pvqConcernType")
	public Set<PvqConcernRate> getPvqConcernRates() {
		return this.pvqConcernRates;
	}

	public void setPvqConcernRates(Set<PvqConcernRate> pvqConcernRates) {
		this.pvqConcernRates = pvqConcernRates;
	}

}
