package in.deepstudio.pvq.domain;

// Generated Apr 22, 2015 12:55:13 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PvqConcernRate generated by hbm2java
 */
@Entity
@Table(name = "pvq_concern_rate",schema="public")
public class PvqConcernRate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long pvqConcernRateId;
	private PvqConcernType pvqConcernType;
	private String pvqConcernName;
	private String pvqConcernRateDesc;
	private String pvqConcernRateAmt;
	private Date createdDate;
	private Date updatedDate;
	private String ipAddress;
	private Set<PvqBillConcernDetail> pvqBillConcernDetails = new HashSet<PvqBillConcernDetail>(0);
	

	public PvqConcernRate() {
	}

	public PvqConcernRate(Long pvqConcernRateId, PvqConcernType pvqConcernType,
			String pvqConcernName,
			String pvqConcernRateAmt, Date createdDate, Date updatedDate,
			String ipAddress) {
		this.pvqConcernRateId = pvqConcernRateId;
		this.pvqConcernType = pvqConcernType;
		this.pvqConcernName = pvqConcernName;
		this.pvqConcernRateAmt = pvqConcernRateAmt;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.ipAddress = ipAddress;
	}

	public PvqConcernRate(Long pvqConcernRateId, PvqConcernType pvqConcernType,String pvqConcernName,
			String pvqConcernRateDesc, String pvqConcernRateAmt,
			Date createdDate, Date updatedDate, String ipAddress ,Set<PvqBillConcernDetail> pvqBillConcernDetails) {
		this.pvqConcernRateId = pvqConcernRateId;
		this.pvqConcernType = pvqConcernType;
		this.pvqConcernName = pvqConcernName;
		this.pvqConcernRateDesc = pvqConcernRateDesc;
		this.pvqConcernRateAmt = pvqConcernRateAmt;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.ipAddress = ipAddress;
		this.pvqBillConcernDetails = pvqBillConcernDetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "pvq_concern_rate_id", unique = true, nullable = false)
	public Long getPvqConcernRateId() {
		return this.pvqConcernRateId;
	}

	public void setPvqConcernRateId(Long pvqConcernRateId) {
		this.pvqConcernRateId = pvqConcernRateId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pvq_concern_type_id", nullable = false)
	public PvqConcernType getPvqConcernType() {
		return this.pvqConcernType;
	}

	public void setPvqConcernType(PvqConcernType pvqConcernType) {
		this.pvqConcernType = pvqConcernType;
	}

	@Column(name = "pvq_concern_name", length = 100)
	public String getPvqConcernName() {
		return pvqConcernName;
	}

	public void setPvqConcernName(String pvqConcernName) {
		this.pvqConcernName = pvqConcernName;
	}

	@Column(name = "pvq_concern_rate_desc", length = 100)
	public String getPvqConcernRateDesc() {
		return this.pvqConcernRateDesc;
	}

	public void setPvqConcernRateDesc(String pvqConcernRateDesc) {
		this.pvqConcernRateDesc = pvqConcernRateDesc;
	}

	@Column(name = "pvq_concern_rate_amt", nullable = false, length = 10)
	public String getPvqConcernRateAmt() {
		return this.pvqConcernRateAmt;
	}

	public void setPvqConcernRateAmt(String pvqConcernRateAmt) {
		this.pvqConcernRateAmt = pvqConcernRateAmt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "ip_address", nullable = false, length = 45)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pvqConcernRate")
	public Set<PvqBillConcernDetail> getPvqBillConcernDetails() {
		return this.pvqBillConcernDetails;
	}

	public void setPvqBillConcernDetails(
			Set<PvqBillConcernDetail> pvqBillConcernDetails) {
		this.pvqBillConcernDetails = pvqBillConcernDetails;
	}

}
