package in.deepstudio.framingcentre.domain;
// default package
// Generated Oct 27, 2014 11:32:10 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FrameDetails generated by hbm2java
 */
@Entity
@Table(name = "frame_details",schema="public")
public class FrameDetails implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6629734935994633875L;
	private Long frameQualifiedId;
	private FrameInfo frameInfo;
	private FrameNumber frameNumber;
	private FrameSize frameSize;
	private FrameThickness frameThickness;
	private String frameDescription;
	private Date createdDate;
	private Date updatedDate;
	private String ipAddress;
	private Set<FrameRate> frameRates = new HashSet<>(0);
	private Set<FrameCustBillingInfoDetail> frameCustBillingInfoDetail = new HashSet<>(0);

	public FrameDetails() {
	}

	public FrameDetails(FrameInfo frameInfo, FrameNumber frameNumber,
			FrameSize frameSize, FrameThickness frameThickness,
			Date createdDate, Date updatedDate, String ipAddress) {
		this.frameInfo = frameInfo;
		this.frameNumber = frameNumber;
		this.frameSize = frameSize;
		this.frameThickness = frameThickness;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.ipAddress = ipAddress;
	}

	public FrameDetails(FrameInfo frameInfo, FrameNumber frameNumber,
			FrameSize frameSize, FrameThickness frameThickness,
			String frameDescription, Date createdDate, Date updatedDate,
			String ipAddress, Set<FrameRate> frameRates, Set<FrameCustBillingInfoDetail> frameCustBillingInfoDetail) {
		this.frameInfo = frameInfo;
		this.frameNumber = frameNumber;
		this.frameSize = frameSize;
		this.frameThickness = frameThickness;
		this.frameDescription = frameDescription;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.ipAddress = ipAddress;
		this.frameRates = frameRates;
		this.setFrameCustBillingInfoDetail(frameCustBillingInfoDetail);
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "frame_qualified_id", unique = true, nullable = false)
	public Long getFrameQualifiedId() {
		return this.frameQualifiedId;
	}

	public void setFrameQualifiedId(Long frameQualifiedId) {
		this.frameQualifiedId = frameQualifiedId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "frame_info_id", nullable = false)
	public FrameInfo getFrameInfo() {
		return this.frameInfo;
	}

	public void setFrameInfo(FrameInfo frameInfo) {
		this.frameInfo = frameInfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "frame_number_id", nullable = false)
	public FrameNumber getFrameNumber() {
		return this.frameNumber;
	}

	public void setFrameNumber(FrameNumber frameNumber) {
		this.frameNumber = frameNumber;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "frame_size_id", nullable = false)
	public FrameSize getFrameSize() {
		return this.frameSize;
	}

	public void setFrameSize(FrameSize frameSize) {
		this.frameSize = frameSize;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "frame_thickness_id", nullable = false)
	public FrameThickness getFrameThickness() {
		return this.frameThickness;
	}

	public void setFrameThickness(FrameThickness frameThickness) {
		this.frameThickness = frameThickness;
	}
	
	@Column(name = "frame_description", length = 200)
	public String getFrameDescription() {
		return this.frameDescription;
	}

	public void setFrameDescription(String frameDescription) {
		this.frameDescription = frameDescription;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "ip_address", nullable = false, length = 25)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "frameDetails")
	public Set<FrameRate> getFrameRates() {
		return this.frameRates;
	}

	public void setFrameRates(Set<FrameRate> frameRates) {
		this.frameRates = frameRates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "frameDetails")
	public Set<FrameCustBillingInfoDetail> getFrameCustBillingInfoDetail() {
		return frameCustBillingInfoDetail;
	}

	public void setFrameCustBillingInfoDetail(
			Set<FrameCustBillingInfoDetail> frameCustBillingInfoDetail) {
		this.frameCustBillingInfoDetail = frameCustBillingInfoDetail;
	}

}
