package in.deepstudio.framingcentre.domain;
// default package
// Generated Oct 27, 2014 11:32:10 PM by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FrameRate generated by hbm2java
 */
@Entity
@Table(name = "frame_rate",schema="public")
public class FrameRate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4737405205249270847L;
	private Long frameRateId;
	private FrameClientType frameClientType;
	private FrameDetails frameDetails;
	private String price;
	private String frameRatePhoto;
	private Date createdDate;
	private Date updatedDate;
	private String ipAddress;

	public FrameRate() {
	}

	public FrameRate(FrameClientType frameClientType,
			FrameDetails frameDetails, String price,String frameRatePhoto ,
			Date createdDate,
			Date updatedDate, String ipAddress) {
		this.frameClientType = frameClientType;
		this.frameDetails = frameDetails;
		this.price = price;
		this.frameRatePhoto=frameRatePhoto;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.ipAddress = ipAddress;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "frame_rate_id", unique = true, nullable = false)
	public Long getFrameRateId() {
		return this.frameRateId;
	}

	public void setFrameRateId(Long frameRateId) {
		this.frameRateId = frameRateId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "client_type_id", nullable = false)
	public FrameClientType getFrameClientType() {
		return this.frameClientType;
	}

	public void setFrameClientType(FrameClientType frameClientType) {
		this.frameClientType = frameClientType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "frame_qualified_id", nullable = true)
	public FrameDetails getFrameDetails() {
		return this.frameDetails;
	}

	public void setFrameDetails(FrameDetails frameDetails) {
		this.frameDetails = frameDetails;
	}

	@Column(name = "price", nullable = false, length = 10)
	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}
	
	@Column(name = "frame_rate_photo", length = 500)
	public String getFrameRatePhoto() {
		return this.frameRatePhoto;
	}

	public void setFrameRatePhoto(String frameRatePhoto) {
		this.frameRatePhoto = frameRatePhoto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "ip_address", nullable = false, length = 25)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

}
