package in.deepstudio.framingcentre.domain;
// default package
// Generated Oct 27, 2014 11:32:10 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * FrameClientType generated by hbm2java
 */
@Entity
@Table(name = "frame_client_type", uniqueConstraints = @UniqueConstraint(columnNames = "client_type_name"),schema="public")
public class FrameClientType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3569321618779050931L;
	private Long clientTypeId;
	private String clientTypeName;
	private String clientDesc;
	private Date createdDate;
	private Date updatedDate;
	private String ipAddress;
	private Set<FrameRate> frameRates = new HashSet<>(0);
	private Set<FrameCustBillingInfoDetail> frameCustBillingInfoDetail = new HashSet<>(0);

	public FrameClientType() {
	}

	public FrameClientType(String clientTypeName, Date createdDate,
			Date updatedDate, String ipAddress) {
		this.clientTypeName = clientTypeName;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.ipAddress = ipAddress;
	}

	public FrameClientType(String clientTypeName, String clientDesc,
			Date createdDate, Date updatedDate, String ipAddress, Set<FrameRate> frameRates, Set<FrameCustBillingInfoDetail> frameCustBillingInfoDetail) {
		this.clientTypeName = clientTypeName;
		this.clientDesc = clientDesc;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.ipAddress = ipAddress;
		this.frameRates = frameRates;
		this.frameCustBillingInfoDetail = frameCustBillingInfoDetail;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "client_type_id", unique = true, nullable = false)
	public Long getClientTypeId() {
		return this.clientTypeId;
	}

	public void setClientTypeId(Long clientTypeId) {
		this.clientTypeId = clientTypeId;
	}

	@Column(name = "client_type_name", unique = true, nullable = false, length = 45)
	public String getClientTypeName() {
		return this.clientTypeName;
	}

	public void setClientTypeName(String clientTypeName) {
		this.clientTypeName = clientTypeName;
	}

	@Column(name = "client_desc", length = 200)
	public String getClientDesc() {
		return this.clientDesc;
	}

	public void setClientDesc(String clientDesc) {
		this.clientDesc = clientDesc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "ip_address", nullable = false, length = 25)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "frameClientType")
	public Set<FrameRate> getFrameRates() {
		return this.frameRates;
	}

	public void setFrameRates(Set<FrameRate> frameRates) {
		this.frameRates = frameRates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "frameClientType")
	public Set<FrameCustBillingInfoDetail> getFrameCustBillingInfoDetail() {
		return frameCustBillingInfoDetail;
	}

	public void setFrameCustBillingInfoDetail(
			Set<FrameCustBillingInfoDetail> frameCustBillingInfoDetail) {
		this.frameCustBillingInfoDetail = frameCustBillingInfoDetail;
	}

}
