package in.deepstudio.framingcentre.domain;

// Generated May 9, 2015 5:00:11 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FrameBillPaymentHistory generated by hbm2java
 */
@Entity
@Table(name = "frame_bill_payment_history",schema="public")
public class FrameBillPaymentHistory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int frameBillPaymentHistoryId;
	private FrameCustBillingInfo frameCustBillingInfo;
	private int frameBillPaymentVersion;
	private String depositeAmount;

	public FrameBillPaymentHistory() {
	}

	public FrameBillPaymentHistory(int frameBillPaymentHistoryId,FrameCustBillingInfo frameCustBillingInfo,
			int custBillingId, int frameBillPaymentVersion,
			String depositeAmount) {
		super();
		this.frameBillPaymentHistoryId = frameBillPaymentHistoryId;
		this.frameCustBillingInfo = frameCustBillingInfo;
		this.frameBillPaymentVersion = frameBillPaymentVersion;
		this.depositeAmount = depositeAmount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "frame_bill_payment_history_id", unique = true, nullable = false)
	public int getFrameBillPaymentHistoryId() {
		return this.frameBillPaymentHistoryId;
	}

	public void setFrameBillPaymentHistoryId(int frameBillPaymentHistoryId) {
		this.frameBillPaymentHistoryId = frameBillPaymentHistoryId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cust_billing_id", nullable = false)
	public FrameCustBillingInfo getFrameCustBillingInfo() {
		return frameCustBillingInfo;
	}
	
	public void setFrameCustBillingInfo(FrameCustBillingInfo frameCustBillingInfo) {
		this.frameCustBillingInfo = frameCustBillingInfo;
	}

	@Column(name = "frame_bill_payment_version", nullable = false)
	public int getFrameBillPaymentVersion() {
		return this.frameBillPaymentVersion;
	}

	public void setFrameBillPaymentVersion(int frameBillPaymentVersion) {
		this.frameBillPaymentVersion = frameBillPaymentVersion;
	}

	@Column(name = "deposite_amount", nullable = false, length = 10)
	public String getDepositeAmount() {
		return this.depositeAmount;
	}

	public void setDepositeAmount(String depositeAmount) {
		this.depositeAmount = depositeAmount;
	}

}
