package in.deepstudio.framingcentre.domain;
// default package
// Generated Oct 27, 2014 11:32:10 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * FrameNumber generated by hbm2java
 */
@Entity
@Table(name = "frame_number", uniqueConstraints = @UniqueConstraint(columnNames = "frame_number"),schema="public")
public class FrameNumber implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 968238716605200626L;
	private Long frameNumberId;
	private String frameNumber;
	private String frameDesc;
	private String frameNumberPhotos;
	private Date createdDate;
	private Date updatedDate;
	private String ipAddress;
	private Set<FrameDetails> frameDetailses = new HashSet<>(0);

	public FrameNumber() {
	}

	public FrameNumber(String frameNumber, Date createdDate, Date updatedDate,
			String ipAddress) {
		this.frameNumber = frameNumber;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.ipAddress = ipAddress;
	}

	public FrameNumber(String frameNumber, String frameDesc,
			String frameNumberPhotos, Date createdDate, Date updatedDate,
			String ipAddress, Set<FrameDetails> frameDetailses) {
		this.frameNumber = frameNumber;
		this.frameDesc = frameDesc;
		this.frameNumberPhotos = frameNumberPhotos;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.ipAddress = ipAddress;
		this.frameDetailses = frameDetailses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "frame_number_id", unique = true, nullable = false)
	public Long getFrameNumberId() {
		return this.frameNumberId;
	}

	public void setFrameNumberId(Long frameNumberId) {
		this.frameNumberId = frameNumberId;
	}

	@Column(name = "frame_number", unique = true, nullable = false, length = 45)
	public String getFrameNumber() {
		return this.frameNumber;
	}

	public void setFrameNumber(String frameNumber) {
		this.frameNumber = frameNumber;
	}

	@Column(name = "frame_desc", length = 200)
	public String getFrameDesc() {
		return this.frameDesc;
	}

	public void setFrameDesc(String frameDesc) {
		this.frameDesc = frameDesc;
	}

	@Column(name = "frame_number_photos", length = 100)
	public String getFrameNumberPhotos() {
		return this.frameNumberPhotos;
	}

	public void setFrameNumberPhotos(String frameNumberPhotos) {
		this.frameNumberPhotos = frameNumberPhotos;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "ip_address", nullable = false, length = 25)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "frameNumber")
	public Set<FrameDetails> getFrameDetailses() {
		return this.frameDetailses;
	}

	public void setFrameDetailses(Set<FrameDetails> frameDetailses) {
		this.frameDetailses = frameDetailses;
	}

}
