package in.deepstudio.framingcentre.domain;
// default package
// Generated Oct 27, 2014 11:32:10 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.DateTimeFormat.ISO;

/**
 * FrameCustBillingInfo generated by hbm2java
 */
@Entity
@Table(name = "frame_cust_billing_info",schema="public")
public class FrameCustBillingInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3835062311705971506L;
	private Long custBillingId;
	private String custName;
	private String custMobno;
	private String custAddress;
	private String custBillNumber;
	private Integer finalBillAmount;
	private Date billDate;
	private String billStatus;
	private String depositeAmount="0";
	private String totalPaidAmount="0";
	private String dueAmount="0";
	private List<FrameCustBillingInfoDetail> frameCustBillingInfoDetail = new ArrayList<>(0);
	private List<FrameBillPaymentHistory> frameBillPaymentHistory = new ArrayList<>(0);
	private Date createdDate;
	private Date updatedDate;
	private String ipAddress;

	public FrameCustBillingInfo() {
	}

	

	public FrameCustBillingInfo(Long custBillingId,
			String custName, String custMobno,
			String custAddress, String custBillNumber,
			Integer finalBillAmount, Date billDate,String billStatus, 
			String totalPaidAmount, String dueAmount,
			Date createdDate,
			Date updatedDate, String ipAddress) {
		super();
		this.custBillingId = custBillingId;
		this.custName = custName;
		this.custMobno = custMobno;
		this.custAddress = custAddress;
		this.custBillNumber = custBillNumber;
		this.finalBillAmount = finalBillAmount;
		this.billDate = billDate;
		this.billStatus = billStatus;
		this.totalPaidAmount = totalPaidAmount;
		this.dueAmount = dueAmount;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.ipAddress = ipAddress;
	}



	public FrameCustBillingInfo(Long custBillingId,
			String custName, String custMobno,
			String custAddress,
			 String custBillNumber,
			Integer finalBillAmount, Date billDate,String billStatus, 
			String totalPaidAmount,String dueAmount,
			List<FrameCustBillingInfoDetail> frameCustBillingInfoDetail,List<FrameBillPaymentHistory> frameBillPaymentHistory,
			Date createdDate, Date updatedDate, String ipAddress) {
		super();
		this.custBillingId = custBillingId;
		this.custName = custName;
		this.custMobno = custMobno;
		this.custAddress = custAddress;
		this.custBillNumber = custBillNumber;
		this.finalBillAmount = finalBillAmount;
		this.billDate = billDate;
		this.billStatus=billStatus;
		this.totalPaidAmount = totalPaidAmount;
		this.dueAmount = dueAmount;
		this.frameBillPaymentHistory = frameBillPaymentHistory;
		this.frameCustBillingInfoDetail = frameCustBillingInfoDetail;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.ipAddress = ipAddress;
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cust_billing_id", unique = true, nullable = false)
	public Long getCustBillingId() {
		return this.custBillingId;
	}

	public void setCustBillingId(Long custBillingId) {
		this.custBillingId = custBillingId;
	}

	@Column(name = "cust_name", nullable = false, length = 50)
	public String getCustName() {
		return this.custName;
	}

	public void setCustName(String custName) {
		this.custName = custName;
	}

	@Column(name = "cust_mobno", length = 15)
	public String getCustMobno() {
		return this.custMobno;
	}

	public void setCustMobno(String custMobno) {
		this.custMobno = custMobno;
	}

	@Column(name = "cust_address", length = 200)
	public String getCustAddress() {
		return this.custAddress;
	}

	public void setCustAddress(String custAddress) {
		this.custAddress = custAddress;
	}
	
	@Column(name = "cust_bill_number", nullable = false, length = 45)
	public String getCustBillNumber() {
		return this.custBillNumber;
	}

	public void setCustBillNumber(String custBillNumber) {
		this.custBillNumber = custBillNumber;
	}

	@Column(name = "final_bill_amount", nullable = false, length = 25)
	public Integer getFinalBillAmount() {
		return finalBillAmount;
	}

	public void setFinalBillAmount(Integer finalBillAmount) {
		this.finalBillAmount = finalBillAmount;
	}

	@DateTimeFormat(iso=ISO.DATE,pattern="dd/MM/yyyy")
	@Column(name = "bill_date", nullable = false, length = 19)
	public Date getBillDate() {
		return billDate;
	}

	public void setBillDate(Date billDate) {
		this.billDate = billDate;
	}
	
	@Column(name = "bill_status")
	public String getBillStatus() {
		return this.billStatus;
	}

	public void setBillStatus(String billStatus) {
		this.billStatus = billStatus;
	}

	@Column(name = "total_paid_amount", nullable = false, length = 10)
	public String getTotalPaidAmount() {
		return this.totalPaidAmount;
	}

	public void setTotalPaidAmount(String totalPaidAmount) {
		this.totalPaidAmount = totalPaidAmount;
	}

	@Column(name = "due_amount", nullable = false, length = 10)
	public String getDueAmount() {
		return this.dueAmount;
	}

	public void setDueAmount(String dueAmount) {
		this.dueAmount = dueAmount;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "frameCustBillingInfo",cascade=CascadeType.ALL)
	public List<FrameCustBillingInfoDetail> getFrameCustBillingInfoDetail() {
		return this.frameCustBillingInfoDetail;
	}

	public void setFrameCustBillingInfoDetail(
			List<FrameCustBillingInfoDetail> frameCustBillingInfoDetail) {
		this.frameCustBillingInfoDetail = frameCustBillingInfoDetail;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "frameCustBillingInfo",cascade=CascadeType.ALL)
	public List<FrameBillPaymentHistory> getFrameBillPaymentHistory() {
		return this.frameBillPaymentHistory;
	}

	public void setFrameBillPaymentHistory(
			List<FrameBillPaymentHistory> frameBillPaymentHistory) {
		this.frameBillPaymentHistory = frameBillPaymentHistory;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "ip_address", nullable = false, length = 25)
	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}
	
	public String getDepositeAmount() {
		return depositeAmount;
	}

	public void setDepositeAmount(String depositeAmount) {
		this.depositeAmount = depositeAmount;
	}


	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("FrameCustBillingInfo [custBillingId=");
		builder.append(custBillingId);
		builder.append(", custName=");
		builder.append(custName);
		builder.append(", custMobno=");
		builder.append(custMobno);
		builder.append(", custAddress=");
		builder.append(custAddress);
		builder.append(", custBillNumber=");
		builder.append(custBillNumber);
		builder.append(", finalBillAmount=");
		builder.append(finalBillAmount);
		builder.append(", billDate=");
		builder.append(billDate);
		builder.append(", frameCustBillingInfoDetail=");
		builder.append(frameCustBillingInfoDetail);
		builder.append(", createdDate=");
		builder.append(createdDate);
		builder.append(", updatedDate=");
		builder.append(updatedDate);
		builder.append(", ipAddress=");
		builder.append(ipAddress);
		builder.append("]");
		return builder.toString();
	}
	
	

}
